name: Build and move files

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build project
      run: |
        cd app
        npm run build

    - name: Delete previous assets and fonts
      run: rm -rf ./assets ./fonts
    
    - name: Move build files to root for Github Pages
      run: mv -f ./app/dist/* ./

    - name: Commit and push build files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add build files" || echo "Nothing to commit"
        git push origin main
