name: Build and move files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build project
      run: |
        cd app
        npm run build
    
    - name: Move build files to root for Github Pages
      run: mv -f ./app/dist/* ./
